create table dagd.pastebin (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ip VARCHAR(45) NOT NULL,
  useragent VARCHAR(255) DEFAULT NULL,
  creation_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);