CREATE TABLE command_redirects (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  author_ip VARCHAR(45) NOT NULL,
  command VARCHAR(10) NOT NULL,
  url VARCHAR(255) NOT NULL,
  creation_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
