CREATE TABLE db_state (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  application VARCHAR(255) NOT NULL UNIQUE,
  file_id INT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
